# Generated by Django 4.0.4 on 2022-11-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
    ]
