# Generated by Django 4.0.4 on 2022-11-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_app', '0003_doctor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
