# Generated by Django 4.0.4 on 2022-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_app', '0004_doctor_city_doctor_country_doctor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=15),
            preserve_default=False,
        ),
    ]
