# Generated by Django 4.0.4 on 2022-11-13 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ark_app', '0007_alter_doctor_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=200)),
                ('is_book', models.BooleanField(default=False)),
            ],
        ),
    ]
