# Generated by Django 4.0.4 on 2022-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_app', '0010_appointment_email_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='doctors/images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='patients/images/'),
        ),
    ]
